name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: iffy/install-nim@v5
    - run: git config --global --add safe.directory "$(pwd)"
    - run: nim r src/all_benchmarks.nim
